#!/bin/bash -eu

# Clone upstream project
UPSTREAM_NAME="druid"
UPSTREAM_REPO="https://github.com/implydata/$UPSTREAM_NAME.git"
UPSTREAM_COMMITISH="druid-0.8.3-iap3"
UPSTREAM_DIR="$TMP_DIR/$UPSTREAM_NAME.git"

# We're including derbytools too
DERBYTOOLS_VERSION="10.11.1.1"

#git clone -b "$UPSTREAM_COMMITISH" --single-branch --depth 1 "$UPSTREAM_REPO" "$UPSTREAM_DIR"
git clone "$UPSTREAM_REPO" "$UPSTREAM_DIR"
(cd "$UPSTREAM_DIR" && git checkout "$UPSTREAM_COMMITISH")

UPSTREAM_COMMIT=$(cd "$UPSTREAM_DIR" && git rev-list --max-count 1 --abbrev-commit HEAD)

# For compatibility with HDP. Revert the Spark indexer and downgrade Jackson.
pushd $UPSTREAM_DIR
git config --global user.email "druidbuilder@example.com"
git config --global user.name "Druid Builder"
echo | git revert b463b6f3a9a32ea59bd66651730ea095e83b0813
sed -i~ 's@<jackson.version>.*</jackson.version>@<jackson.version>2.2.3</jackson.version>@' pom.xml
popd

# Build upstream project, skipTests because tests were already run on this tag
(cd "$UPSTREAM_DIR" && mvn package -DskipTests)

# Stage upstream project
mkdir -p "$STAGING_DIR/dist"
tar -C "$TMP_DIR" -xzf "$UPSTREAM_DIR"/distribution/target/druid-*-bin.tar.gz
mv "$TMP_DIR"/druid-* "$STAGING_DIR/dist/druid"

# Run pull-deps for all builtin extensions
java \
  -cp "$STAGING_DIR/dist/druid/lib/*" \
  -Ddruid.extensions.coordinates='["io.druid.extensions:druid-azure-extensions", "io.druid.extensions:druid-datasketches", "io.druid.extensions:druid-examples", "io.druid.extensions:druid-hdfs-storage", "io.druid.extensions:druid-histogram", "io.druid.extensions:druid-kafka-eight", "io.druid.extensions:druid-kafka-extraction-namespace", "io.druid.extensions:druid-namespace-lookup", "io.druid.extensions:druid-rabbitmq", "io.druid.extensions:druid-s3-extensions", "io.druid.extensions:mysql-metadata-storage", "io.druid.extensions:postgresql-metadata-storage"]' \
  -Ddruid.extensions.localRepository="$STAGING_DIR/dist/druid/extensions-repo" \
  io.druid.cli.Main tools pull-deps

# Add derbytools to lib
DERBYTOOLS_LOCATION="$STAGING_DIR/dist/druid/lib/derbytools-$DERBYTOOLS_VERSION.jar"
curl -Lo "$DERBYTOOLS_LOCATION" "http://search.maven.org/remotecontent?filepath=org/apache/derby/derbytools/$DERBYTOOLS_VERSION/derbytools-$DERBYTOOLS_VERSION.jar"

if [ "$(sha1sum "$DERBYTOOLS_LOCATION" | awk '{print $1}')" != "10a124a8962c6f8ea70a368d711ce6883889ca34" ]
then
  echo "$DERBYTOOLS_LOCATION: checksum mismatch" >&2
  exit 1
fi

# Put druid on a diet
for JAR in "$STAGING_DIR"/dist/druid/lib/*.jar
do
  JARNAME="$(basename "$JAR")"
  FOUND="$(cd "$STAGING_DIR"/dist/druid && find extensions-repo -name "$JARNAME")"
  if [ "x$FOUND" != "x" ]
  then
    ln -sf "../$FOUND" "$JAR"
  fi
done

# Write version
UPSTREAM_COMMIT="$(cd "$UPSTREAM_DIR" && git rev-list --max-count 1 --abbrev-commit HEAD)"
echo -n "-$UPSTREAM_NAME-$UPSTREAM_COMMIT" >> "$TMP_DIR/version.txt"
