drop database foodmart_parquet cascade;
create database if not exists foodmart_parquet;
use foodmart_parquet;
DROP TABLE IF EXISTS warehouse_class;
DROP TABLE IF EXISTS warehouse;
DROP TABLE IF EXISTS time_by_day;
DROP TABLE IF EXISTS store_ragged;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS sales_fact_dec_1998;
DROP TABLE IF EXISTS sales_fact_1998;
DROP TABLE IF EXISTS sales_fact_1997;
DROP TABLE IF EXISTS salary;
DROP TABLE IF EXISTS reserve_employee;
DROP TABLE IF EXISTS region;
DROP TABLE IF EXISTS promotion;
DROP TABLE IF EXISTS product_class;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS position;
DROP TABLE IF EXISTS inventory_fact_1998;
DROP TABLE IF EXISTS inventory_fact_1997;
DROP TABLE IF EXISTS expense_fact;
DROP TABLE IF EXISTS employee_closure;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS days;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS currency;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS agg_pl_01_sales_fact_1997;
DROP TABLE IF EXISTS agg_ll_01_sales_fact_1997;
DROP TABLE IF EXISTS agg_lc_100_sales_fact_1997;
DROP TABLE IF EXISTS agg_lc_06_sales_fact_1997;
DROP TABLE IF EXISTS agg_l_05_sales_fact_1997;
DROP TABLE IF EXISTS agg_l_04_sales_fact_1997;
DROP TABLE IF EXISTS agg_l_03_sales_fact_1997;
DROP TABLE IF EXISTS agg_g_ms_pcat_sales_fact_1997;
DROP TABLE IF EXISTS agg_c_special_sales_fact_1997;
DROP TABLE IF EXISTS agg_c_14_sales_fact_1997;
DROP TABLE IF EXISTS agg_c_10_sales_fact_1997;
DROP TABLE IF EXISTS account;
CREATE TABLE warehouse_class stored as parquet as select * from foodmart.warehouse_class;
CREATE TABLE warehouse stored as parquet as select * from foodmart.warehouse;
CREATE TABLE time_by_day stored as parquet as select * from foodmart.time_by_day;
CREATE TABLE store_ragged stored as parquet as select * from foodmart.store_ragged;
CREATE TABLE store stored as parquet as select * from foodmart.store;
CREATE TABLE sales_fact_dec_1998 stored as parquet as select * from foodmart.sales_fact_dec_1998;
CREATE TABLE sales_fact_1998 stored as parquet as select * from foodmart.sales_fact_1998;
CREATE TABLE sales_fact_1997 stored as parquet as select * from foodmart.sales_fact_1997;
CREATE TABLE sales_fact_1997 stored as parquet as select * from foodmart.sales_fact_1997;
CREATE TABLE salary stored as parquet as select * from foodmart.salary;
CREATE TABLE reserve_employee stored as parquet as select * from foodmart.reserve_employee;
CREATE TABLE region stored as parquet as select * from foodmart.region;
CREATE TABLE promotion stored as parquet as select * from foodmart.promotion;
CREATE TABLE product_class stored as parquet as select * from foodmart.product_class;
CREATE TABLE product stored as parquet as select * from foodmart.product;
CREATE TABLE position stored as parquet as select * from foodmart.position;
CREATE TABLE inventory_fact_1998 stored as parquet as select * from foodmart.inventory_fact_1998;
CREATE TABLE inventory_fact_1997 stored as parquet as select * from foodmart.inventory_fact_1997;
CREATE TABLE expense_fact stored as parquet as select * from foodmart.expense_fact;
CREATE TABLE employee_closure stored as parquet as select * from foodmart.employee_closure;
CREATE TABLE employee stored as parquet as select * from foodmart.employee;
CREATE TABLE department stored as parquet as select * from foodmart.department;
CREATE TABLE days stored as parquet as select * from foodmart.days;
CREATE TABLE customer stored as parquet as select * from foodmart.customer;
CREATE TABLE currency stored as parquet as select * from foodmart.currency;
CREATE TABLE category stored as parquet as select * from foodmart.category;
CREATE TABLE agg_pl_01_sales_fact_1997 stored as parquet as select * from foodmart.agg_pl_01_sales_fact_1997;
CREATE TABLE agg_ll_01_sales_fact_1997 stored as parquet as select * from foodmart.agg_ll_01_sales_fact_1997;
CREATE TABLE agg_lc_100_sales_fact_1997 stored as parquet as select * from foodmart.agg_lc_100_sales_fact_1997;
CREATE TABLE agg_lc_06_sales_fact_1997 stored as parquet as select * from foodmart.agg_lc_06_sales_fact_1997;
CREATE TABLE agg_l_05_sales_fact_1997 stored as parquet as select * from foodmart.agg_l_05_sales_fact_1997;
CREATE TABLE agg_l_04_sales_fact_1997 stored as parquet as select * from foodmart.agg_l_04_sales_fact_1997;
CREATE TABLE agg_l_03_sales_fact_1997 stored as parquet as select * from foodmart.agg_l_03_sales_fact_1997;
CREATE TABLE agg_g_ms_pcat_sales_fact_1997 stored as parquet as select * from foodmart.agg_g_ms_pcat_sales_fact_1997;
CREATE TABLE agg_c_special_sales_fact_1997 stored as parquet as select * from foodmart.agg_c_special_sales_fact_1997;
CREATE TABLE agg_c_14_sales_fact_1997 stored as parquet as select * from foodmart.agg_c_14_sales_fact_1997;
CREATE TABLE agg_c_10_sales_fact_1997 stored as parquet as select * from foodmart.agg_c_10_sales_fact_1997;
CREATE TABLE account stored as parquet as select * from foodmart.account;
